println("I know scala!")
println("Scala is a really kewl language")
println("It compiles into jvm bytecode")
println("What does that mean? It means that scala and java can be combined.")
println("You can compile the whole shizaam with the scala compiler, and then you can package into a jar file")
println("I use the scala-ide plugin for eclipse to automatically use the correct compiler when packaging a jar")
println("The only issue with the plugin is that it doesn't allow you to set the main class of a jar to be a scala file with a SCALA main method.")
println("You can only set files with a JAVA main method to be the main class of a jar :(")
println("So, sadly, I have to have a java main class which runs the scala main class's main method")