println("I know scala!")
println("Scala is a really kewl language")
println("It compiles into jvm bytecode")
println("What does that mean? It means that scala and java can be combined.")
println("You can compile the whole shizaam with the scala compiler, and then you can package into a jar file")
println("I use the scala-ide plugin for eclipse to automatically use the correct compiler when packaging a jar")